package api

import (
	"context"
	"encoding/json"
	"fmt"
	"net/http"
	"strings"

	"github.com/luiacuaniello/perspectivegraph/internal/ai"
	"github.com/luiacuaniello/perspectivegraph/internal/analyzer"
	"github.com/luiacuaniello/perspectivegraph/internal/auth"
	remediationpkg "github.com/luiacuaniello/perspectivegraph/internal/remediation"
)

// WithAI attaches the AI-native layer (NL query / exec summary / path
// explanation). A nil or Nop client disables the /ai/* endpoints. Returns the
// API for chaining.
func (a *API) WithAI(c ai.Client) *API {
	a.ai = c
	return a
}

func (a *API) aiEnabled() bool { return a.ai != nil && a.ai.Enabled() }

// handleAISummary handles GET /ai/summary — an executive summary of the tenant's
// current posture, generated by Claude from the live attack paths.
func (a *API) handleAISummary(w http.ResponseWriter, r *http.Request) {
	if !a.requireAI(w) {
		return
	}
	system := "You are a principal security analyst briefing executives. Be factual, concise, and non-alarmist. " +
		"Ground every statement in the data provided — do not invent assets or numbers. Respond with 4–6 plain sentences " +
		"(no markdown headings, no bullet lists): the headline risk, what is actively exploited, and the single most important fix."
	user := "Current attack-path data for the environment:\n\n" + a.pathContext(r.Context(), 15) + "\n\nWrite the executive summary."
	a.runAI(w, r, "ai.summary", system, user)
}

// handleAIQuery handles POST /ai/query {question} — a natural-language question
// answered strictly from the tenant's attack-path graph.
func (a *API) handleAIQuery(w http.ResponseWriter, r *http.Request) {
	if !a.requireAI(w) {
		return
	}
	var req struct {
		Question string `json:"question"`
	}
	if err := json.NewDecoder(http.MaxBytesReader(w, r.Body, 8<<10)).Decode(&req); err != nil {
		writeJSONError(w, http.StatusBadRequest, "invalid JSON body")
		return
	}
	if strings.TrimSpace(req.Question) == "" {
		writeJSONError(w, http.StatusBadRequest, "question is required")
		return
	}
	system := "You answer questions about an organization's attack-path graph using ONLY the data provided below. " +
		"If the data does not contain the answer, say so plainly rather than guessing. Be concise and specific, and cite path numbers when relevant."
	user := a.pathContext(r.Context(), 20) + "\n\nQuestion: " + strings.TrimSpace(req.Question)
	a.runAI(w, r, "ai.query", system, user)
}

// handleAIExplain handles POST /ai/explain {pathId} — a plain-English walk-through
// of one attack path and the single most effective fix.
func (a *API) handleAIExplain(w http.ResponseWriter, r *http.Request) {
	if !a.requireAI(w) {
		return
	}
	var req struct {
		PathID string `json:"pathId"`
	}
	if err := json.NewDecoder(http.MaxBytesReader(w, r.Body, 8<<10)).Decode(&req); err != nil {
		writeJSONError(w, http.StatusBadRequest, "invalid JSON body")
		return
	}
	path, ok := findPath(a.scopedLatest(r.Context()), req.PathID)
	if !ok {
		writeJSONError(w, http.StatusNotFound, "attack path not found (or out of your scope)")
		return
	}
	system := "You explain a single attack path to an engineer in plain English: how an attacker would walk it step by step, " +
		"why it matters (what sits at the end), and the single most effective fix to break it. Be concise and concrete, no preamble."
	a.runAI(w, r, "ai.explain", system, "Attack path:\n"+pathDetail(path))
}

// requireAI writes a 503 and returns false when the AI layer isn't configured.
func (a *API) requireAI(w http.ResponseWriter) bool {
	if !a.aiEnabled() {
		writeJSONError(w, http.StatusServiceUnavailable, "AI features are not configured (set ANTHROPIC_API_KEY)")
		return false
	}
	return true
}

// runAI calls the model, audits the call (the attack map left the trust boundary),
// and returns the answer.
func (a *API) runAI(w http.ResponseWriter, r *http.Request, action, system, user string) {
	answer, err := a.ai.Complete(r.Context(), system, user)
	if err != nil {
		writeJSONError(w, http.StatusBadGateway, "AI request failed: "+err.Error())
		return
	}
	p := auth.PrincipalFromContext(r.Context())
	a.audit.Record(action, p.Subject, p.Role.String(), p.Tenant, map[string]any{"answer_chars": len(answer)})
	writeJSON(w, http.StatusOK, map[string]any{"answer": answer})
}

// pathContext renders the tenant's top attack paths as a compact, grounded
// context block for the model — capped to bound token usage.
func (a *API) pathContext(ctx context.Context, limit int) string {
	paths := a.scopedLatest(ctx)
	if len(paths) == 0 {
		return "There are currently no internet-exposed attack paths to a crown jewel."
	}
	var b strings.Builder
	shown := min(limit, len(paths))
	fmt.Fprintf(&b, "There are %d critical attack paths (internet-exposed entry → crown jewel). Top %d by triage priority:\n", len(paths), shown)
	for i := 0; i < shown; i++ {
		fmt.Fprintf(&b, "%d. %s\n", i+1, pathLine(paths[i]))
	}
	return b.String()
}

// pathLine renders one path as a single line: priority, the kill chain, exploit
// score, runtime status, and the priority factors.
func pathLine(p analyzer.AttackPath) string {
	var b strings.Builder
	if p.PriorityLabel != "" {
		fmt.Fprintf(&b, "[%s pri=%.0f] ", p.PriorityLabel, p.Priority)
	}
	for i, n := range p.Nodes {
		if i > 0 && i-1 < len(p.Steps) {
			fmt.Fprintf(&b, " -%s-> ", p.Steps[i-1].EdgeType)
		}
		name := n.Name
		if name == "" {
			name = n.ID
		}
		b.WriteString(name)
		if i == len(p.Nodes)-1 {
			fmt.Fprintf(&b, " [%s]", n.Label)
		}
	}
	fmt.Fprintf(&b, " | exploit %.0f%%", p.Score*100)
	if p.RuntimeConfirmed {
		b.WriteString(" | RUNTIME-CONFIRMED")
	}
	if len(p.PriorityFactors) > 0 {
		fmt.Fprintf(&b, " | %s", strings.Join(p.PriorityFactors, ", "))
	}
	return b.String()
}

// pathDetail renders one path with its kill chain and the remediation hints, for
// the explain endpoint.
func pathDetail(p analyzer.AttackPath) string {
	var b strings.Builder
	b.WriteString(pathLine(p))
	b.WriteString("\n")
	if hints := remediationpkg.Hints(p); len(hints) > 0 {
		b.WriteString("Candidate fixes (cutting any one edge breaks the path):\n")
		for _, h := range hints {
			fmt.Fprintf(&b, "- %s\n", h)
		}
	}
	return b.String()
}
