import { useState } from "react";
import { aiQuery, aiSummary } from "../api/client";

// AssistantView is the AI-native surface: a board-level executive summary and a
// natural-language Q&A over the current attack-path graph. Both are answered by
// Claude, grounded in the live data the backend already has - nothing is invented.
export default function AssistantView() {
  const [summary, setSummary] = useState<string | null>(null);
  const [summaryBusy, setSummaryBusy] = useState(false);
  const [summaryErr, setSummaryErr] = useState<string | null>(null);

  const [question, setQuestion] = useState("");
  const [answer, setAnswer] = useState<string | null>(null);
  const [answerBusy, setAnswerBusy] = useState(false);
  const [answerErr, setAnswerErr] = useState<string | null>(null);

  const runSummary = () => {
    setSummaryBusy(true);
    setSummaryErr(null);
    aiSummary()
      .then(setSummary)
      .catch((e) => setSummaryErr(String(e.message ?? e)))
      .finally(() => setSummaryBusy(false));
  };

  const ask = () => {
    const q = question.trim();
    if (!q) return;
    setAnswerBusy(true);
    setAnswerErr(null);
    setAnswer(null);
    aiQuery(q)
      .then(setAnswer)
      .catch((e) => setAnswerErr(String(e.message ?? e)))
      .finally(() => setAnswerBusy(false));
  };

  return (
    <div className="flex flex-col gap-4 px-4 pb-10 sm:px-8">
      <div>
        <h2 className="text-lg font-semibold text-slate-900">AI assistant</h2>
        <p className="mt-0.5 text-[13px] text-slate-500">
          Answers are generated by Claude and grounded in your current attack paths - the data leaves the trust
          boundary on each call (audited).
        </p>
      </div>

      {/* Executive summary */}
      <section className="rounded-xl border border-edge bg-panel p-5 shadow-card">
        <div className="flex items-center justify-between gap-3">
          <h3 className="text-[15px] font-semibold text-slate-800">Executive summary</h3>
          <button
            onClick={runSummary}
            disabled={summaryBusy}
            className="rounded-lg bg-accent px-3 py-1.5 text-[13px] font-medium text-white transition hover:opacity-90 disabled:opacity-60"
          >
            {summaryBusy ? "Generating…" : summary ? "Regenerate" : "Generate"}
          </button>
        </div>
        <p className="mt-1 text-[12px] text-slate-500">A board-ready brief of the current posture.</p>
        {summaryErr && <p className="mt-3 text-[13px] text-red-600">{summaryErr}</p>}
        {summary && (
          <p className="mt-3 whitespace-pre-wrap text-[14px] leading-relaxed text-slate-700">{summary}</p>
        )}
      </section>

      {/* Natural-language Q&A */}
      <section className="rounded-xl border border-edge bg-panel p-5 shadow-card">
        <h3 className="text-[15px] font-semibold text-slate-800">Ask about your attack surface</h3>
        <p className="mt-1 text-[12px] text-slate-500">
          e.g. <span className="text-slate-600">"which internet-exposed path reaches customer PII fastest?"</span>
        </p>
        <div className="mt-3 flex flex-wrap items-center gap-2">
          <input
            value={question}
            onChange={(e) => setQuestion(e.target.value)}
            onKeyDown={(e) => e.key === "Enter" && ask()}
            placeholder="Ask a question about the graph…"
            className="min-w-[16rem] flex-1 rounded-lg border border-edge bg-ink px-3 py-2 text-sm text-slate-800 outline-none focus:border-accent"
          />
          <button
            onClick={ask}
            disabled={answerBusy || !question.trim()}
            className="rounded-lg bg-accent px-4 py-2 text-sm font-medium text-white transition hover:opacity-90 disabled:opacity-60"
          >
            {answerBusy ? "Thinking…" : "Ask"}
          </button>
        </div>
        {answerErr && <p className="mt-3 text-[13px] text-red-600">{answerErr}</p>}
        {answer && (
          <p className="mt-3 whitespace-pre-wrap text-[14px] leading-relaxed text-slate-700">{answer}</p>
        )}
      </section>
    </div>
  );
}
